services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Form\:
        resource: '../src/Form/'

    App\Form\Admin\ArticleFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Article\ArticleFormType }

    App\Form\Admin\AdministratorFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Administrator\AdministratorFormType }

    App\Form\Admin\BrandFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\Brand\BrandFormType }

    App\Form\Admin\CategoryFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Category\CategoryFormType }

    App\Form\Admin\UserFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Customer\UserFormType }

    App\Form\Admin\OrderFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Order\OrderFormType }

    App\Form\Admin\TransportFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Transport\TransportFormType }

    App\Form\Admin\ProductFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Product\ProductFormType }

    App\Form\Admin\PaymentFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Payment\PaymentFormType }
