parameters:
    database_driver: pdo_pgsql
    database_server_version: 10.5
    # Symfony's FrameworkBundle sets throw_at (error_reporting) to 0 in production by default
    debug.error_handler.throw_at: -1
    locale: en
    # Performance test parameters
    shopsys.performance_data.category.counts_by_level: [2, 4, 6]
    shopsys.performance_data.product.total_count: 40000
    shopsys.performance_data.user.count_per_domain: 100
    shopsys.performance_data.order.total_count: 50000
    shopsys.performance_data.order.item_count_per_order: 6
    shopsys.performance_test.page.duration_milliseconds.warning: 1000
    shopsys.performance_test.page.duration_milliseconds.critical: 3000
    shopsys.performance_test.page.query_count.warning: 100
    shopsys.performance_test.page.query_count.critical: 300
    shopsys.performance_test.feed.max_duration_seconds: 180
    shopsys.performance_test.feed.delivery.max_duration_seconds: 20
    shopsys.performance_test.feed.min_duration_seconds: 5
    container.autowiring.strict_mode: true
    shopsys.entity_extension.map:
        Shopsys\FrameworkBundle\Model\Article\Article: App\Model\Article\Article
        Shopsys\FrameworkBundle\Model\Administrator\Administrator: App\Model\Administrator\Administrator
        Shopsys\FrameworkBundle\Model\Category\Category: App\Model\Category\Category
        Shopsys\FrameworkBundle\Model\Customer\User: App\Model\Customer\User
        Shopsys\FrameworkBundle\Model\Order\Order: App\Model\Order\Order
        Shopsys\FrameworkBundle\Model\Order\Item\OrderItem: App\Model\Order\Item\OrderItem
        Shopsys\FrameworkBundle\Model\Transport\Transport: App\Model\Transport\Transport
        Shopsys\FrameworkBundle\Model\Payment\Payment: App\Model\Payment\Payment
        Shopsys\FrameworkBundle\Model\Product\Product: App\Model\Product\Product
        Shopsys\FrameworkBundle\Model\Product\Brand\Brand: App\Model\Product\Brand\Brand
    build-version: '0000000000000000'
    shopsys.display_timezone: Europe/Prague
