imports:
    - { resource: parameters_test.yaml }

framework:
    test: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        class: Tests\App\Functional\EntityExtension\OverwritableEntityNameResolver
        arguments:
            - "%shopsys.entity_extension.map%"

    Tests\App\Functional\EntityExtension\OverwritableEntityNameResolver:
        alias: Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver

    Tests\App\Functional\EntityExtension\OverwritableEntityExtensionSubscriber:
        arguments:
            $entityExtensionMap: '%shopsys.entity_extension.map%'
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }

    Symfony\Bridge\Twig\Extension\HttpKernelRuntime:
        arguments: ['@fragment.handler']

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    League\Flysystem\FilesystemInterface:
        alias: main_filesystem
