parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_NAME): ''

doctrine:
    dbal:
        charset: UTF8
        # Explicitly define server version to overcome the need to connect to the database in early
        # initialization phase (during DIC service creation) for auto-detecting version from the server.
        # See \Doctrine\DBAL\Connection::getDatabasePlatformVersion().
        server_version: "%database_server_version%"
        url: '%env(resolve:DATABASE_URL)%'
        dbname: "%env(resolve:DATABASE_NAME)%"
        types:
            money: \Shopsys\FrameworkBundle\Component\Doctrine\MoneyType

    orm:
        auto_generate_proxy_classes: false
        dql:
            string_functions:
                collate: Shopsys\FrameworkBundle\Component\Doctrine\CollateFunction
                normalize: Shopsys\FrameworkBundle\Component\Doctrine\NormalizeFunction
                field: Shopsys\FrameworkBundle\Component\Doctrine\FieldFunction
        naming_strategy: doctrine.orm.naming_strategy.underscore
        metadata_cache_driver:
            type: service
            id: shopsys.doctrine.cache_driver.metadata_cache
        query_cache_driver:
            type: service
            id: shopsys.doctrine.cache_driver.query_cache
        auto_mapping: false
        mappings:
            ShopsysFrameworkBundle:
                type: annotation
                dir: '%shopsys.framework.root_dir%/src/Model'
                alias: ShopsysFrameworkBundle
                prefix: Shopsys\FrameworkBundle\Model
                is_bundle: false
            ShopsysFrameworkBundleComponent:
                type: annotation
                dir: '%shopsys.framework.root_dir%/src/Component'
                alias: ShopsysFrameworkBundleComponent
                prefix: Shopsys\FrameworkBundle\Component
                is_bundle: false
            App:
                type: annotation
                dir: '%shopsys.root_dir%/src/Model'
                alias: App
                prefix: App\Model
                is_bundle: false
            AppComponent:
                type: annotation
                dir: '%shopsys.root_dir%/src/Component'
                alias: AppComponent
                prefix: App\Component
                is_bundle: false
        hydrators:
            GroupedScalarHydrator: \Shopsys\FrameworkBundle\Component\Doctrine\GroupedScalarHydrator
