framework:
    annotations:
        cache: file
        file_cache_dir: '%kernel.cache_dir%/annotations'
    secret: "%env(APP_SECRET)%"
    router:
        utf8: true
        strict_requirements: true
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    trusted_hosts: ~
    session:
        storage_factory_id: session.storage.factory.native
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_httponly: true
        # Disable the default PHP session garbage collection.
        # Session garbage collection is responsibility of hosting.
        gc_probability: 0
        cookie_lifetime: 31536000 # 365 days * 24 hours * 3600 seconds
    fragments: ~
    http_method_override: true
    profiler:
        enabled: false
        collect: false
    assets: ~
    error_controller: 'Shopsys\FrameworkBundle\Component\Error\ErrorController::showAction'
