overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: yaml
                    dir: "%shopsys.root_dir%/config/graphql/types"
        builders:
            args:
                -   alias: "PaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\PaginatorArgumentsBuilder
