snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:bestselling_products:'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine:query:'
        # client is used exclusively for cleaning old versions of redis caches and should not be used for anything else
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        session:
            type: 'phpredis'
            alias: 'session'
            dsn: 'redis://%redis_host%'
    session:
        client: 'session'
        ttl: 604800
        prefix: '%env(REDIS_PREFIX)%session:'
