parameters:
    # name of the monorepo package, for UPGRADE.md and CHANGELOG.md links
    monorepo_package_name: "shopsys/shopsys"

    # these stages can use already existing tag; newer version than the last one is required in all other stages by default
    # this can be used to skip the tag validation completely
    # we need this as we are supporting multiple versions and we need to release tags that are lower than the newest one
    # e.g. we want to release "v7.3.2" even if "v8.0.0" is already released
    stages_to_allow_existing_tag:
        - "release-candidate"
        - "release"
        - "after-release"

services:
    _defaults:
        autowire: true

    Shopsys\Releaser\:
        resource: "../src"
        exclude: "../src/Exception"

    GuzzleHttp\Client: ~
    Symfony\Component\Console\Helper\QuestionHelper: ~

    Shopsys\Releaser\FilesProvider\ComposerJsonFilesProvider:
        arguments:
            - ['packages', 'project-base']

    Twig_Environment:
        class: Twig\Environment

    Twig_LoaderInterface:
        class: Twig\Loader\FilesystemLoader
        arguments:
            - ['upgrade/template']
