
extra_css:
    - _theme/main.css

markdown_extensions:
    -   toc:
            permalink: True
            toc_depth: 2-4
    - admonition

plugins:
    -   awesome-pages:
            filename: navigation.yml
    - search

site_name: Shopsys Platform Docs

theme:
    custom_dir: "docs/_theme"
    hljs_style: vs2015
    hljs_languages:
        - dockerfile
        - less
        - twig
        - yaml
    name: readthedocs
