site_name: Shopsys Framework Docs

theme:
    name: readthedocs
    hljs_languages:
        - dockerfile
        - twig
        - yaml
        - less

extra_css:
    - _theme/extra.css

markdown_extensions:
    - toc:
          permalink: True
          toc_depth: 2-3
    - admonition

plugins:
    - search
    - awesome-pages:
          filename: navigation.yml
