OrderItemDecorator:
    type: object
    decorator: true
    config:
        description: "Represent one item in the order"
        fields:
            name:
                type: "String!"
                description: "Name of the order item"
            unitPrice:
                type: "Price!"
                description: "Order item price per unit"
            totalPrice:
                type: "Price!"
                description: "Total price for the quantity of order item"
            vatRate:
                type: "String!"
                description: "Applied VAT rate percentage applied to the order item"
            quantity:
                type: "Int!"
                description: "Quantity of order items in the order"
            unit:
                type: "String"
                description: "Unit of measurement used for the order item"
            uuid:
                type: "Uuid!"
                description: "UUID of the order item"
            catnum:
                type: "String"
                description: "Catalog number of the order item product"
            order:
                type: "Order!"
                description: "Order to which the order item belongs"
            type:
                type: "OrderItemTypeEnum!"
                description: "Type of the order item"
            productMainImage:
                type: "Image"
                description: "Product main image by params"
