TransportDecorator:
    type: interface
    decorator: true
    config:
        description: "Represents a transport"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Transport name"
            description:
                type: "String"
                description: "Localized transport description (domain dependent)"
            instruction:
                type: "String"
                description: "Localized transport instruction (domain dependent)"
            position:
                type: "Int!"
                description: "Transport position"
            price:
                type: "Price!"
                description: "Transport price"
                resolve: '@=query("priceByTransportQuery", value, args["cartUuid"], context)'
                args:
                    cartUuid:
                        type: "Uuid"
                        defaultValue: null
            images:
                type: "[Image!]!"
                description: "Transport images"
                resolve: '@=query("imagesByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            payments:
                type: "[Payment!]!"
                description: "List of assigned payments"
            transportTypeCode:
                type: "TransportTypeEnum!"
                description: "Code of transport type"
