monolog:
    handlers:
        main:
            type: fingers_crossed
            buffer_size: 1000
            action_level: warning
            handler: sentry
            excluded_http_codes: [{ 404: ['^/'] }, { 405: ['^/'] }]
