ProductConnection:
    type: relay-connection
    config:
        nodeType: Product
        connectionFields:
            totalCount:
                type: "Int!"
                description: "Total number of products (-1 means that the total count is not available)"
            productFilterOptions:
                type: "ProductFilterOptions!"
            orderingMode:
                type: "ProductOrderingModeEnum!"
                description: "The current ordering mode"
            defaultOrderingMode:
                type: "ProductOrderingModeEnum"
                description: "The default ordering mode that is set for the given connection (e.g. in a category, search page, or ready category SEO mix)"
    inherits:
        - 'ProductConnectionDecorator'
