CategoryDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a category"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String"
                description: "Localized category name (domain dependent)"
            children:
                type: "[Category!]"
                description: "Descendant categories"
            parent:
                type: "Category"
                description: "Ancestor category"
            images:
                type: "[Image!]!"
                description: "Category images"
                resolve: '@=query("imagesByEntityQuery", value, args["type"], args["size"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    size:
                        type: "String"
            products:
                type: "ProductConnection"
                description: "Paginated and ordered products of category"
                argsBuilder:
                    builder: "PaginatorArgumentsBuilder"
                    config:
                        orderingModeType: 'ProductOrderingModeEnum'
                resolve: '@=query("productsByCategoryQuery", args, value)'
            seoH1:
                type: "String"
                description: "Seo first level heading of category"
            seoTitle:
                type: "String"
                description: "Seo title of category"
            seoMetaDescription:
                type: "String"
                description: "Seo meta description of category"
