ChangePasswordInputDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            email:
                type: "String!"
                description: "Customer user email."
                validation:
                    -   NotBlank:
                            message: "Please enter your email address"
            oldPassword:
                type: "String!"
                description: "Current customer user password."
                validation:
                    -   NotBlank:
                            message: "Please enter old password"
                    -   Length:
                            min: 6
                            minMessage: "Old password must be at least {{ limit }} characters long"
            newPassword:
                type: "String!"
                description: "New customer user password."
                validation:
                    -   NotBlank:
                            message: "Please enter new password"
                    -   Length:
                            min: 6
                            minMessage: "New password must be at least {{ limit }} characters long"
