PriceDecorator:
    type: object
    decorator: true
    config:
        description: "Represents the price"
        fields:
            priceWithVat:
                type: "Money!"
                description: "Price with VAT"
            priceWithoutVat:
                type: "Money!"
                description: "Price without VAT"
            vatAmount:
                type: "Money!"
                description: "Total value of VAT"
