SettingsDecorator:
    type: object
    decorator: true
    config:
        description: "Represents settings of the current domain"
        fields:
            seo:
                type: "SeoSetting!"
                resolve: "@=query('seoSettingsQuery')"
                description: "Settings related to SEO"
            maxAllowedPaymentTransactions:
                type: Int!
                resolve: "@=query('maxAllowedPaymentTransactionsQuery')"
                description: "Max allowed payment transactions (how many times is user allowed to try the same payment)"
            pricing:
                type: "PricingSetting!"
                resolve: "@=query('pricingSettingsQuery')"
                description: "Settings related to pricing"
            contactFormMainText:
                type: String!
                resolve: "@=query('contactFormMainTextQuery')"
                description: "Main text for contact form"
            displayTimezone:
                type: String!
                resolve: "@=query('displayTimezoneQuery')"
                description: "Timezone that is used for displaying time"
            mainBlogCategoryUrl:
                type: String
                resolve: "@=query('mainBlogCategoryUrlQuery')"
                description: "Absolute URL of the blog main category"
            heurekaEnabled:
                type: Boolean!
                resolve: "@=query('heurekaEnabledQuery')"
                description: "Returns true if Heureka is available for the current domain"
            termsAndConditionsArticleUrl:
                type: String
                resolve: "@=query('termsAndConditionsArticleUrlQuery')"
                description: "Returns Terms and Conditions article's url"
            privacyPolicyArticleUrl:
                type: String
                resolve: "@=query('privacyPolicyArticleUrlQuery')"
                description: "Returns privacy policy article's url"
            userConsentPolicyArticleUrl:
                type: String
                resolve: "@=query('userConsentPolicyArticleUrlQuery')"
                description: "Returns User consent policy article's url"
