Query:
    type: object
    inherits:
        - 'QueryDecorator'
        - 'NavigationQuery'
        - 'CustomerUserQuery'
        - 'CategoryQuery'
        - 'StoreQuery'
        - 'SliderQuery'
        - 'FlagQuery'
        - 'OrderQuery'
        - 'PersonalDataQuery'
        - 'ProductQuery'
        - 'SlugQuery'
        - 'NotificationBarQuery'
        - 'CartQuery'
        - 'TransportQuery'
        - 'CountryQuery'
        - 'LanguageConstantQuery'
        - 'SeoPageQuery'
