ProductDecorator:
    type: interface
    decorator: true
    config:
        description: "Represents a product"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String"
                description: "Localized product name (domain dependent)"
            shortDescription:
                type: "String"
                description: "Localized product short description (domain dependent)"
            usps:
                type: "[String!]!"
                description: "List of product's unique selling propositions"
            link:
                type: "String!"
                description: "Product link"
            unit:
                type: "Unit!"
            availability:
                type: "Availability"
            stockQuantity:
                type: "Int"
                description: "Count of quantity on stock"
            categories:
                type: "[Category!]!"
                description: "List of categories"
            flags:
                type: "[Flag!]!"
                description: "List of flags"
            price:
                type: "ProductPrice"
                description: "Product price"
                resolve: '@=query("priceByProductQuery", value)'
            images:
                type: "[Image]!"
                description: "Product images"
                resolve: '@=query("imagesByProductPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            brand:
                type: "Brand"
                description: "Brand of product"
            isSellingDenied:
                type: "Boolean!"
            orderingPriority:
                type: "Int!"
            description:
                type: "String"
            accessories:
                type: "[Product]"
            parameters:
                type: "[Parameter]!"
            seoH1:
                type: "String"
                description: "Seo first level heading of product"
            seoTitle:
                type: "String"
                description: "Seo title of product"
            seoMetaDescription:
                type: "String"
                description: "Seo meta description of product"
            hreflangLinks:
                type: "[HreflangLink!]!"
                description: "Alternate links for hreflang meta tags"
            files:
                type: "[File!]!"
                resolve: '@=query("filesByProductPromiseQuery", value)'
            isVisible:
                type: "Boolean!"
