domains:
    -   id: 1
        name: shopsys
        locale: en
        styles_directory: common
        timezone: Europe/Prague

    -   id: 2
        name: 2.shopsys
        locale: cs
        styles_directory: domain2
        timezone: Europe/Prague
