# Example:
#-   name: product
#    class: Shopsys\FrameworkBundle\Model\Product\Product
#    types:
#        -   name: gallery
#            multiple: true
#        -   name: main

-   name: payment
    class: Shopsys\FrameworkBundle\Model\Payment\Payment

-   name: category
    class: Shopsys\FrameworkBundle\Model\Category\Category

-   name: product
    class: Shopsys\FrameworkBundle\Model\Product\Product
    multiple: true

-   name: sliderItem
    class: Shopsys\FrameworkBundle\Model\Slider\SliderItem
    types:
        -   name: web
        -   name: mobile

-   name: transport
    class: Shopsys\FrameworkBundle\Model\Transport\Transport

-   name: noticer
    class: Shopsys\FrameworkBundle\Model\Advert\Advert
    types:
        -   name: web
        -   name: mobile

-   name: brand
    class: Shopsys\FrameworkBundle\Model\Product\Brand\Brand

-   name:  blogCategory
    class: Shopsys\FrameworkBundle\Model\Blog\Category\BlogCategory

-   name:  blogArticle
    class: Shopsys\FrameworkBundle\Model\Blog\Article\BlogArticle

-   name: notificationBar
    class: App\Model\NotificationBar\NotificationBar

-   name: store
    class: Shopsys\FrameworkBundle\Model\Store\Store
    multiple: true

-   name: seoPage
    class: App\Model\SeoPage\SeoPage
    types:
        -   name: og
