on:
    schedule:
        -   cron: '0 3 * * *'
    workflow_dispatch:
name: Rebuild PHP Image for branches
jobs:
    rebuild-php-images:
        name: Rebuild ${{ matrix.branches }} branch
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                branches: ['13.0', '14.0']
            fail-fast: false
        permissions:
            contents: read
        steps:
            -   name: GIT checkout branch - refs/heads/${{ matrix.branches }}
                uses: actions/checkout@v4
                with:
                    ref: refs/heads/${{ matrix.branches }}
            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -   name: Docker Setup Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Build PHP-FPM image and push it to DockerHub
                run: |
                    TAG=shopsys/php-image:${{ matrix.branches }}
                    docker buildx build --push --tag ${TAG} --no-cache --platform linux/arm64,linux/amd64 --compress -f ./Dockerfile .
