parameters:
    shopsys.content_dir_name: 'content'
    shopsys.customer_uploaded_file_config_filepath: '%kernel.project_dir%/config/customer_uploaded_files.yaml'
    shopsys.customer_uploaded_file_dir: '/var/customerUploadedFiles/'
    shopsys.data_fixtures.resources_dir: '%kernel.project_dir%/src/DataFixtures/resources'
    shopsys.data_fixtures_images.resources_dir: '%shopsys.data_fixtures.resources_dir%/images/'
    shopsys.data_fixtures_uploaded_files.resources_dir: '%shopsys.data_fixtures.resources_dir%/uploaded_files/'
    shopsys.default_db_schema_filepath: '%shopsys.framework.resources_dir%/database/schema.sql'
    shopsys.domain_config_filepath: '%kernel.project_dir%/config/domains.yaml'
    shopsys.domain_images_dir: '/web%shopsys.domain_images_url_prefix%'
    shopsys.domain_images_url_prefix: '/%shopsys.content_dir_name%/admin/images/domain'
    shopsys.domain_urls_config_filepath: '%kernel.project_dir%/config/domains_urls.yaml'
    shopsys.elasticsearch.structure_dir: '%shopsys.resources_dir%/definition/'
    shopsys.error_pages_dir: '/var/errorPages/'
    shopsys.feed_dir: '/web%shopsys.feed_url_prefix%'
    shopsys.feed_url_prefix: '/%shopsys.content_dir_name%/feeds/'
    shopsys.filemanager_upload_dir: '%shopsys.web_dir%/%shopsys.filemanager_upload_web_dir%'
    shopsys.filemanager_upload_web_dir: '%shopsys.content_dir_name%/wysiwyg'
    shopsys.framework.root_dir: '%kernel.project_dir%/vendor/shopsys/framework'
    shopsys.front_design_image_url_prefix: /public/frontend/images/
    shopsys.image_config_filepath: '%kernel.project_dir%/config/images.yaml'
    shopsys.image_dir: '/web%shopsys.image_url_prefix%'
    shopsys.image_url_prefix: '/%shopsys.content_dir_name%/images/'
    shopsys.json_entrypoints_path: '%kernel.project_dir%/web/build/entrypoints.json'
    shopsys.locale_file_dir: '/web%shopsys.locale_file_url_prefix%'
    shopsys.locale_file_url_prefix: '/%shopsys.content_dir_name%/locales/'
    shopsys.log_stream: /tmp/log-pipe
    shopsys.product_files_dir: '/web%shopsys.product_files_url_prefix%'
    shopsys.product_files_url_prefix: '/%shopsys.content_dir_name%/frontend/products/'
    shopsys.resources_dir: '%kernel.project_dir%/src/Resources'
    shopsys.sitemaps_dir: '/web%shopsys.sitemaps_url_prefix%'
    shopsys.sitemaps_url_prefix: '/%shopsys.content_dir_name%/sitemaps'
    shopsys.uploaded_file_config_filepath: '%kernel.project_dir%/config/uploaded_files.yaml'
    shopsys.uploaded_file_dir: '/web%shopsys.uploaded_file_url_prefix%'
    shopsys.uploaded_file_url_prefix: '/%shopsys.content_dir_name%/uploadedFiles/'
    shopsys.var_dir: '/var'
    shopsys.vendor_dir: '%kernel.project_dir%/vendor'
    shopsys.web_dir: '%kernel.project_dir%/web'
