twig:
    debug: "%kernel.debug%"
    exception_controller: null
    form_themes:
        - '@ShopsysFramework/Admin/Form/Product/Price/pricesWithCalculatedSellingPricesType.html.twig'
        - '@ShopsysFramework/Admin/Form/Product/Price/productPricesWithVatSelectType.html.twig'
        - '@ShopsysFramework/Admin/Form/abstractFileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/abstractMultiplePicker.html.twig'
        - '@ShopsysFramework/Admin/Form/blogCategoriesType.html.twig'
        - '@ShopsysFramework/Admin/Form/blogCategoryCheckboxType.html.twig'
        - '@ShopsysFramework/Admin/Form/colorpickerFields.html.twig'
        - '@ShopsysFramework/Admin/Form/complaintItems.html.twig'
        - '@ShopsysFramework/Admin/Form/customerUserListFields.html.twig'
        - '@ShopsysFramework/Admin/Form/deliveryAddressListFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyCompanyName.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyCustomer.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyDomainIconFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyOrder.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyUrl.html.twig'
        - '@ShopsysFramework/Admin/Form/displayVariablesFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/fileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/hreflangSettingFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/imageuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/localizedFullWidth.html.twig'
        - '@ShopsysFramework/Admin/Form/mailWhitelistFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/multiLocaleBasicFileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/multiLocaleFileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/orderItems.html.twig'
        - '@ShopsysFramework/Admin/Form/orderlistFields.html.twig'
        - '@ShopsysFramework/Admin/Form/parameterValueConversionList.html.twig'
        - '@ShopsysFramework/Admin/Form/paymentTransactionsFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/priceandvattableByDomainsFields.html.twig'
        - '@ShopsysFramework/Admin/Form/productParameterValue.html.twig'
        - '@ShopsysFramework/Admin/Form/promoCodeFlagFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/promoCodeLimitFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/rolesType.html.twig'
        - '@ShopsysFramework/Admin/Form/storeOpeningHoursFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/transportPricesFormTheme.html.twig'
        - '@ShopsysFramework/Admin/Form/warningMessage.html.twig'
        - 'Admin/Form/grapesJsMailType.html.twig'
        - 'Admin/Form/grapesJsType.html.twig'
        - 'Admin/Form/languageConstantFormTheme.html.twig'
        - 'Admin/Form/productDetailFormTheme.html.twig'
        - 'Admin/Form/productVideoValue.html.twig'
        - 'Admin/Form/productsFormTheme.html.twig'
    globals:
        globalMultipleFormSetting: '@Shopsys\FrameworkBundle\Component\Form\MultipleFormSetting'
        usersnapApiKey: '%env(USERSNAP_PROJECT_API_KEY)%'
    strict_variables: true
