BlogCategoryDecorator:
    type: object
    decorator: true
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
            - 'Hreflang'
        fields:
            uuid:
                type: "Uuid!"
                description: "The blog category UUID"
            name:
                type: "String!"
                description: "The blog category name"
            description:
                type: "String"
                description: "The blog category description"
            parent:
                type: "BlogCategory"
                description: "The blog category parent"
            children:
                type: "[BlogCategory!]!"
                description: "The blog category children"
            seoTitle:
                type: "String"
                description: "The blog category SEO title"
            seoMetaDescription:
                type: "String"
                description: "The blog category SEO meta description"
            seoH1:
                type: "String"
                description: "The blog category SEO H1 heading"
            blogArticles:
                type: "BlogArticleConnection!"
                description: "Paginated blog articles of the given blog category"
                argsBuilder: "BlogArticlePaginatorArgumentsBuilder"
                resolve: '@=query("blogArticleByCategoryQuery", args, value)'
            link:
                type: "String!"
                description: "The blog category absolute URL"
            slug:
                type: "String!"
                description: "The blog category URL slug"
            mainImage:
                type: "Image"
                description: "Blog category image"
                resolve: '@=query("mainImageByBlogCategoryPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
                resolve: '@=query("breadcrumbQuery", value.getId(), "front_blogcategory_detail")'
            blogCategoriesTree:
                type: "[BlogCategory!]!"
                description: "Tho whole blog categories tree (used for blog navigation rendering)"
            articlesTotalCount:
                type: "Int!"
                description: "Total count of blog articles in this category"
            hreflangLinks:
                type: "[HreflangLink!]!"
                description: "Alternate links for hreflang meta tags"
